var partners = [
  {
    "partner": "AARP",
    "website": "https://local.aarp.org/charlotte-nc/",
    "strategies": ["a", "d", "j", "k", "l", "n", "p", "u"],
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Health",
      "Learning",
      "Safe Community",
    ],
  },
  {
    "partner": "AIA",
    "website": "http://www.aiacharlotte.org/",
    "strategies": ["g", "k", "s"],
  },
  {
    "partner": "Active Charlotte",
    "website": "http://activecharlotte.org/",
    "strategies": ["p"],
    "thinktanks": ["Accessibility", "Health"],
  },
  {
    "partner": "Ada Jenkins Center",
    "website": "http://www.adajenkins.org/",
    "strategies": ["l", "m"],
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Culture Connections",
      "Health",
      "Learning",
      "Natural Resources",
      "Safe Community",
    ],
  },
  {
    "partner": "American Leadership Forum Charlotte",
    "website": "http://alfcharlotteregion.org/",
    "strategies": ["u"],
    "thinktanks": ["Culture Connections"],
  },
  {
    "partner": "Arts and Science Council",
    "website": "http://www.artsandscience.org/",
    "strategies": ["c", "d", "j", "m"],
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Inviting Destination",
      "Learning",
      "Natural Resources",
      "Redevelopment",
    ],
  },
  {
    "partner": "Camino Community Center",
    "website": "https://caminohealthcenter.com/",
    "thinktanks": ["At-Risk Residents", "Culture Connections", "Health"],
  },
  {
    "partner": "Cardinal Innovations",
    "website": "http://www.cardinalinnovations.org/",
    "strategies": ["i", "p"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Health",
      "Inviting Destination",
      "Learning",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Care Ring",
    "website": "http://www.careringnc.org/",
    "strategies": ["p"],
    "thinktanks": ["At-Risk Residents", "Health", "Safe Community"],
  },
  {
    "partner": "Carolina Thread Trail",
    "website": "http://www.carolinathreadtrail.org/",
    "strategies": ["d", "i", "m", "r", "t"],
    "thinktanks": [
      "Accessibility",
      "Culture Connections",
      "Health",
      "Inviting Destination",
    ],
  },
  {
    "partner": "Carolina Voices",
    "website": "https://www.carolinavoices.org/",
    "strategies": ["b", "n"],
    "thinktanks": ["Culture Connections", "Learning"],
  },
  {
    "partner": "Carolinas Healthcare System",
    "website": "http://www.carolinashealthcare.org/",
    "strategies": ["f", "p"],
    "thinktanks": ["Accessibility", "Health", "Safe Community"],
  },
  {
    "partner": "Catawba Land Conservancy",
    "website": "http://catawbalands.org/",
    "strategies": ["d", "i", "q", "r", "s", "t"],
  },
  {
    "partner": "Catawba Riverkeeper",
    "website": "http://www.catawbariverkeeper.org/",
    "strategies": ["q", "t"],
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Culture Connections",
      "Health",
      "Inviting Destination",
      "Learning",
      "Natural Resources",
      "Redevelopment",
    ],
  },
  {
    "partner": "Catholic Refugee Resettlement Office",
    "website": "https://ccdoc.org/refugee-language",
    "thinktanks": ["At-Risk Residents"],
  },
  {
    "partner": "Center for Prevention Services",
    "website": "http://www.preventionservices.org/",
    "strategies": ["p"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Health",
      "Learning",
      "Safe Community",
    ],
  },
  {
    "partner": "Central Piedmont Community College",
    "website": "http://www.cpcc.edu/",
    "strategies": ["b", "e", "f", "h", "n", "o", "u"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
      "Natural Resources",
    ],
  },
  {
    "partner": "Centralina Council of Governments",
    "website": "http://www.centralina.org/",
    "strategies": ["e", "f", "g", "i", "k", "p", "q", "s", "t"],
    "thinktanks": [
      "Accessibility",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Inviting Destination",
      "Learning",
      "Natural Resources",
      "Redevelopment",
    ],
  },
  {
    "partner": "Centralina Council on Aging",
    "website":
      "http://www.centralina.org/centralina-area-agency-on-aging-home/services/",
    "thinktanks": ["Accessibility", "Health"],
  },
  {
    "partner": "Charlotte Area Health Education Center",
    "website": "https://www.charlotteahec.org/",
    "strategies": ["p"],
    "thinktanks": ["Culture Connections", "Health", "Learning"],
  },
  {
    "partner": "Charlotte Area Transit System",
    "website": "http://charmeck.org/city/charlotte/cats/Pages/default.aspx",
    "strategies": ["c", "g", "i"],
    "thinktanks": ["Accessibility"],
  },
  {
    "partner": "Charlotte Center City Partners",
    "website": "http://www.charlottecentercity.org/",
    "strategies": [
      "b",
      "c",
      "d",
      "e",
      "f",
      "g",
      "h",
      "i",
      "j",
      "l",
      "o",
      "q",
      "s",
      "t",
      "u",
    ],
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
      "Inviting Destination",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Charlotte Chamber of Commerce",
    "website": "http://charlottechamber.com/",
    "strategies": ["c", "e", "f", "g", "h", "i", "o", "p", "q", "s", "u"],
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
      "Inviting Destination",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Charlotte Department of Transportation",
    "website":
      "http://charmeck.org/city/charlotte/Transportation/Pages/Home.aspx",
    "strategies": ["i", "p", "s"],
    "thinktanks": ["Accessibility", "Natural Resources"],
  },
  {
    "partner": "Charlotte Economic Development",
    "website": "https://charlottenc.gov/ed/Pages/default.aspx",
    "strategies": ["e"],
    "thinktanks": ["Economic Competitiveness"],
  },
  {
    "partner": "Charlotte Engineering and Property Management",
    "website": "http://charmeck.org/city/charlotte/epm/Pages/default.aspx",
    "strategies": ["e", "g", "i", "q", "r", "s", "t"],
  },
  {
    "partner": "Charlotte Family Housing",
    "website": "http://charlottefamilyhousing.org/",
    "strategies": ["g", "k", "t"],
  },
  {
    "partner": "Charlotte Fire Department",
    "website": "http://charmeck.org/city/charlotte/Fire/Pages/default.aspx",
    "strategies": ["a"],
    "thinktanks": ["Safe Community"],
  },
  {
    "partner": "Inlivian",
    "website": "https://www.inlivian.com/",
    "strategies": ["k", "t"],
  },
  {
    "partner": "Charlotte International Cabinet",
    "website":
      "https://charlottenc.gov/HNS/EMII/Pages/Charlotte-International-Cabinet.aspx",
    "strategies": ["c", "f", "n"],
  },
  {
    "partner": "Charlotte Mecklenburg Police Department",
    "website": "http://charmeck.org/city/charlotte/CMPD/Pages/default.aspx",
    "strategies": ["a", "i"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Inviting Destination",
      "Safe Community",
    ],
  },
  {
    "partner": "Charlotte Museum of History",
    "website": "http://www.charlottemuseum.org/",
    "strategies": ["b", "c", "d"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Inviting Destination",
      "Learning",
      "Natural Resources",
    ],
  },
  {
    "partner": "Charlotte Neighborhood and Business Services",
    "website": "http://charmeck.org/city/charlotte/nbs/Pages/default.aspx",
    "strategies": [
      "a",
      "d",
      "g",
      "h",
      "i",
      "j",
      "o",
      "p",
      "q",
      "r",
      "s",
      "t",
      "u",
    ],
  },
  {
    "partner": "Charlotte Regional Transportation Planning Organization",
    "website": "http://www.crtpo.org/",
    "strategies": ["d", "i", "q", "s"],
    "thinktanks": ["Accessibility", "Economic Competitiveness"],
  },
  {
    "partner": "Charlotte Rescue Mission",
    "website": "http://charlotterescuemission.org/",
    "strategies": ["l"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Inviting Destination",
      "Learning",
      "Safe Community",
    ],
  },
  {
    "partner": "Charlotte Solid Waste Services",
    "website": "http://charmeck.org/city/charlotte/SWS/Pages/Home.aspx",
    "strategies": ["u"],
  },
  {
    "partner": "Charlotte Strategy & Budget",
    "website": "https://charlottenc.gov/budget/Pages/default.aspx",
    "thinktanks": ["At-Risk Residents", "Natural Resources"],
  },
  {
    "partner": "Charlotte Water",
    "website": "http://charmeck.org/city/charlotte/Utilities/Pages/Home.aspx",
    "thinktanks": ["Natural Resources"],
  },
  {
    "partner": "Charlotte Works",
    "website": "http://www.charlotteworks.com/",
    "strategies": ["f", "n", "o"],
    "thinktanks": [
      "At-Risk Residents",
      "Economic Competitiveness",
      "Inviting Destination",
      "Learning",
    ],
  },
  {
    "partner": "Charlotte-Mecklenburg Food Policy Council",
    "website": "https://charlottefoodpolicy.com/",
    "strategies": ["p"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Inviting Destination",
      "Learning",
      "Natural Resources",
      "Redevelopment",
    ],
  },
  {
    "partner": "Charlotte-Mecklenburg Historic Landmarks Commission",
    "website": "http://www.cmhpf.org/",
    "strategies": ["a", "d", "g"],
  },
  {
    "partner": "Dream Key Partners",
    "website": "https://dreamkeypartners.org/",
    "strategies": ["g", "k", "t"],
    "thinktanks": [
      "Accessibility",
      "Culture Connections",
      "Economic Competitiveness",
      "Inviting Destination",
      "Learning",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Charlotte-Mecklenburg Library",
    "website": "http://www.cmlibrary.org/",
    "strategies": ["b", "c", "d", "f", "g", "h", "j", "m", "n", "o", "u"],
    "thinktanks": ["Culture Connections", "Economic Competitiveness"],
  },
  {
    "partner": "Charlotte-Mecklenburg Planning Department",
    "website": "http://charmeck.org/city/charlotte/planning/Pages/Home.aspx",
    "strategies": ["b", "c", "d", "g", "k", "p", "s"],
    "thinktanks": ["Natural Resources"],
  },
  {
    "partner": "Charlotte-Mecklenburg Schools",
    "website": "http://www.cms.k12.nc.us/Pages/default.aspx",
    "strategies": ["a", "b", "d", "f", "h", "i", "m", "n", "o", "p", "t", "u"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
      "Inviting Destination",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Charlotte-Mecklenburg Utility Department",
    "website": "http://charmeck.org/city/charlotte/Utilities/Pages/Home.aspx",
    "strategies": ["e", "q", "r", "s", "t"],
  },
  {
    "partner": "Child Care Resources",
    "website": "http://www.childcareresourcesinc.org/",
    "strategies": ["l", "n"],
  },
  {
    "partner": "Children and Family Services Center",
    "website": "http://childrenfamily.org/",
    "strategies": ["l"],
  },
  {
    "partner": "Circle de Luz",
    "website": "http://circledeluz.org/",
    "strategies": ["c", "d", "j", "l"],
    "thinktanks": ["At-Risk Residents", "Culture Connections", "Learning"],
  },
  {
    "partner": "Citizen Schools",
    "website": "https://www.citizenschools.org/catalyst",
    "strategies": ["l", "n", "o"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
      "Safe Community",
    ],
  },
  {
    "partner": "City of Charlotte Innovation & Technology Department",
    "website": "http://charmeck.org/city/charlotte/Pages/default.aspx",
    "thinktanks": ["Economic Competitiveness", "Learning"],
  },
  {
    "partner": "City Startup Labs",
    "website": "http://citystartuplabs.com/",
    "thinktanks": ["Economic Competitiveness"],
  },
  {
    "partner": "Clean Air Carolina",
    "website": "http://cleanaircarolina.org/",
    "strategies": ["i", "p", "q", "t"],
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
      "Inviting Destination",
      "Natural Resources",
      "Safe Community",
    ],
  },
  {
    "partner": "CLT Joules",
    "website": "http://cltjoules.com/#/",
    "strategies": ["e", "f", "h", "t"],
    "thinktanks": [
      "Culture Connections",
      "Economic Competitiveness",
      "Inviting Destination",
      "Learning",
      "Natural Resources",
    ],
  },
  {
    "partner": "Code for Charlotte",
    "website": "https://opencharlotte.org/",
    "strategies": ["u"],
    "thinktanks": ["Culture Connections", "Economic Competitiveness", "Learning"],
  },
  {
    "partner": "Community Building Initiative",
    "website": "http://cbicharlotte.org/",
    "thinktanks": ["At-Risk Residents", "Culture Connections"],
  },
  {
    "partner": "Community Care Partners of Greater Mecklenburg",
    "website": "https://www.communitycarenc.org/",
    "strategies": [],
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Culture Connections",
      "Health",
      "Learning",
      "Inviting Destination",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Community Link",
    "website": "http://communitylinknc.org/",
    "strategies": ["l"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Council for Children's Rights",
    "website": "http://www.crckids.org/chapters/north-carolina/",
    "strategies": ["b", "l", "p"],
  },
  {
    "partner": "Crescent Communities",
    "website": "http://www.crescentcommunities.com/Default.aspx",
    "strategies": ["g", "t"],
  },
  {
    "partner": "Crisis Assistance Ministry",
    "website": "http://www.crisisassistance.org/",
    "strategies": ["a", "l", "p"],
  },
  {
    "partner": "Charlotte Wildlife Stewards",
    "website": "https://www.charlottewildlife.org/",
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Inviting Destination",
      "Learning",
      "Natural Resources",
      "Redevelopment",
    ],
  },
  {
    "partner": "Davidson College",
    "website": "http://www.davidson.edu/",
    "strategies": ["e", "f", "h", "n", "o", "u"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Learning",
      "Natural Resources",
    ],
  },
  {
    "partner": "Davidson Housing Coalition",
    "website": "http://davidsonhousing.org/",
    "thinktanks": ["Redevelopment"],
  },
  {
    "partner": "Davidson Land Conservancy",
    "website": "http://www.davidsonlands.org/",
    "strategies": ["d", "i", "q", "r", "s", "t"],
    "thinktanks": ["Accessibility", "Natural Resources"],
  },
  {
    "partner": "Davidson Lifeline",
    "website": "http://www.davidsonlifeline.org/",
    "thinktanks": ["Health"],
  },
  {
    "partner": "Discovery Place",
    "website": "http://www.discoveryplace.org/",
    "strategies": ["b", "c", "m", "n", "o", "u"],
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
      "Inviting Destination",
      "Natural Resources",
      "Redevelopment",
    ],
  },
  {
    "partner": "Duke Energy",
    "website": "http://www.duke-energy.com/north-carolina.asp",
    "strategies": ["f", "h", "s", "t"],
    "thinktanks": ["Natural Resources", "Safe Community"],
  },
  {
    "partner": "E2D",
    "website": "http://www.e-2-d.org/",
    "strategies": ["e", "f", "h", "t"],
    "thinktanks": ["At-Risk Residents", "Learning"],
  },
  {
    "partner": "Envision  Charlotte",
    "website": "http://www.envisioncharlotte.com/",
    "strategies": ["h", "t"],
  },
  {
    "partner": "F3 Foundation",
    "website": "http://f3nation.com/f3-foundation/",
    "thinktanks": ["Health"],
  },
  {
    "partner": "For Charlotte",
    "website": "https://forcharlotte.org/",
    "strategies": ["a", "d", "k", "l", "o", "u"],
    "thinktanks": ["At-Risk Residents", "Culture Connections", "Learning"],
  },
  {
    "partner": "Foresite Development Inc",
    "website": "http://www.forsiteinc.com/",
    "strategies": ["g", "t"],
    "thinktanks": ["Redevelopment"],
  },
  {
    "partner": "Four Town Alliance",
    "strategies": ["c", "e", "f", "g", "h", "i", "o", "p", "q", "s", "u"],
  },
  {
    "partner": "Generation Nation",
    "website": "http://www.generationnation.org/",
    "strategies": ["b", "n", "o", "u"],
    "thinktanks": ["At-Risk Residents", "Culture Connections", "Learning"],
  },
  {
    "partner": "Goodwill Industries",
    "website": "http://www.goodwillsp.org/",
    "strategies": ["h", "l", "n", "o"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
    ],
  },
  {
    "partner": "Greater Charlotte Apartment Association",
    "website": "http://www.greatercaa.org/",
    "strategies": ["g", "j", "t"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Greater Charlotte Hospitality and Tourism Alliance",
    "website": "http://www.charlottehta.com/",
    "strategies": ["c", "d", "m"],
  },
  {
    "partner": "Out Teach",
    "website": "https://www.out-teach.org/carolinas-region-partnerships/",
    "thinktanks": ["Economic Competitiveness", "Health", "Learning"],
  },
  {
    "partner": "Habitat for Humanity Charlotte",
    "website": "http://www.habitatcharlotte.org/",
    "strategies": ["g", "k", "l", "s"],
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Culture Connections",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Hands On Charlotte",
    "website": "http://www.handsoncharlotte.org/",
    "strategies": ["a", "l", "u"],
    "thinktanks": ["Culture Connections", "Inviting Destination"],
  },
  {
    "partner": "Historic Charlotte",
    "website": "http://www.historiccharlotte.org/",
    "strategies": ["b", "d", "g"],
    "thinktanks": ["At-Risk Residents", "Health", "Learning", "Safe Community"],
  },
  {
    "partner": "Historic Landmarks Commission",
    "website": "http://www.cmhpf.org/",
    "thinktanks": ["Culture Connections", "Learning"],
  },
  {
    "partner": "Homeless Services Network",
    "website": "http://solvethepuzzlecharlotte.org/",
    "strategies": ["k"],
    "thinktanks": ["At-Risk Residents", "Redevelopment"],
  },
  {
    "partner": "InnerVision",
    "website": "http://innervisionnc.org/",
    "strategies": ["n"],
    "thinktanks": ["At-Risk Residents", "Health"],
  },
  {
    "partner": "International House",
    "website": "http://www.ihclt.org/",
    "thinktanks": ["Culture Connections"],
  },
  {
    "partner": "Junior Achievement",
    "website": "http://www.jacarolinas.org/",
    "strategies": ["b", "n", "o", "u"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Learning",
      "Safe Community",
    ],
  },
  {
    "partner": "Keep Charlotte Beautiful",
    "website": "https://charlottenc.gov/HNS/CE/KCB/Pages/default.aspx",
    "strategies": ["q", "t"],
    "thinktanks": [
      "Culture Connections",
      "Inviting Destination",
      "Learning",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Keep Mecklenburg Beautiful",
    "website":
      "https://www.mecknc.gov/LUESA/SolidWaste/Community-Programs/Pages/Keep-Mecklenburg-Beautiful-(KMB).aspx",
    "strategies": ["q", "t"],
    "thinktanks": ["Natural Resources"],
  },
  {
    "partner": "Lake Norman Regional Economic Development Corporation",
    "website": "http://www.lakenormanregion.com/",
    "strategies": ["c", "e", "f", "g", "j", "n", "o"],
    "thinktanks": [
      "Economic Competitiveness",
      "Inviting Destination",
      "Learning",
      "Redevelopment",
    ],
  },
  {
    "partner": "Leadership Charlotte",
    "website": "http://leadershipcharlotte.org/",
    "strategies": ["b", "e", "j", "u"],
    "thinktanks": [
      "Culture Connections",
      "Inviting Destination",
      "Safe Community",
    ],
  },
  {
    "partner": "Learning Help Centers of Charlotte",
    "website": "http://www.lhcclt.org/",
    "strategies": ["l", "n", "o"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
      "Inviting Destination",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Levine Museum of the New South",
    "website": "http://www.museumofthenewsouth.org/",
    "strategies": ["b", "c", "d", "m"],
    "thinktanks": ["Culture Connections", "Inviting Destination", "Learning"],
  },
  {
    "partner": "Levine Senior Center",
    "website": "http://www.levineseniorcenter.org/",
    "strategies": ["a", "d", "j", "k", "l", "n", "p", "u"],
  },
  {
    "partner": "MEDIC",
    "website": "https://www.medic911.com/",
    "strategies": ["a"],
    "thinktanks": ["Safe Community"],
  },
  {
    "partner": "Matthews Chamber of Commerce",
    "website": "https://matthewschamber.org/",
    "strategies": [],
    "thinktanks": [],
  },
  {
    "partner": "Matthews Free Medical Clinic",
    "website": "http://www.matthewsfmc.org/",
    "strategies": ["l", "p"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Health",
      "Inviting Destination",
      "Learning",
      "Natural Resources",
      "Safe Community",
    ],
  },
  {
    "partner": "Matthews Help Center",
    "website": "http://www.matthewshelpcenter.org/",
    "strategies": ["l", "p"],
  },
  {
    "partner": "McColl Center",
    "website": "http://mccollcenter.org/",
    "strategies": ["b", "c", "d", "m"],
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
      "Inviting Destination",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "MeckEd",
    "website": "http://www.mecked.org/",
    "strategies": ["b", "n", "o"],
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Mecklenburg County Asset and Facility Management",
    "website": "https://www.mecknc.gov/AFM/Pages/Home.aspx",
    "strategies": ["g", "i", "q", "r", "s", "t"],
    "thinktanks": [
      "Accessibility",
      "Culture Connections",
      "Natural Resources",
      "Redevelopment",
    ],
  },
  {
    "partner": "Mecklenburg County Community Support Services",
    "website": "https://www.mecknc.gov/communitysupportservices",
    "strategies": ["a", "k", "l", "p"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Health",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Mecklenburg County Criminal Justice Services",
    "website": "https://www.mecknc.gov/criminaljusticeservices",
    "strategies": ["a", "p"],
  },
  {
    "partner": "Mecklenburg County Department of Social Services",
    "website": "https://www.mecknc.gov/dss",
    "strategies": ["i", "l", "n", "p"],
    "thinktanks": ["At-Risk Residents", "Accessibility", "Health", "Learning"],
  },
  {
    "partner": "Mecklenburg County Economic Development",
    "website": "https://www.mecknc.gov/oed",
    "strategies": ["e"],
  },
  {
    "partner": "Mecklenburg County Fire Marshall",
    "website":
      "https://www.mecknc.gov/LUESA/CodeEnforcement/Fire-Marshal/Pages/default.aspx",
    "strategies": ["a"],
  },
  {
    "partner": "Mecklenburg County Health Department",
    "website": "https://www.mecknc.gov/healthdepartment",
    "strategies": ["h", "i", "p", "r"],
    "thinktanks": ["Health"],
  },
  {
    "partner": "Mecklenburg County Land Use and Environmental Services Agency",
    "website": "https://www.mecknc.gov/luesa",
    "strategies": ["e", "g", "h", "i", "p", "q", "r", "s", "t", "u"],
    "thinktanks": [
      "Accessibility",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Natural Resources",
      "Redevelopment",
    ],
  },
  {
    "partner": "Mecklenburg County Park and Recreation",
    "website": "https://www.mecknc.gov/parkandrec",
    "strategies": ["b", "d", "g", "h", "i", "j", "m", "p", "q", "r", "s"],
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Culture Connections",
      "Health",
      "Learning",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Mecklenburg County Sheriff's Office",
    "website": "http://www.mecksheriff.com/",
    "strategies": ["a"],
    "thinktanks": ["Safe Community"],
  },
  {
    "partner": "Mecklenburg County Volunteer Fireman's Association",
    "website": "https://www.facebook.com/MECKCVFA",
    "strategies": ["a"],
  },
  {
    "partner": "Mental Health Association of the Central Carolinas",
    "website": "http://www.mhacentralcarolinas.org/",
    "strategies": ["l", "p"],
    "thinktanks": ["At-Risk Residents", "Health"],
  },
  {
    "partner": "Mint Hill Chamber of Commerce",
    "website": "http://www.minthillchamberofcommerce.com/",
    "strategies": ["c", "e", "f", "g", "h", "i", "o", "q", "s", "u"],
    "thinktanks": [
      "Culture Connections",
      "Economic Competitiveness",
      "Inviting Destination",
      "Redevelopment",
    ],
  },
  {
    "partner": "My Aloha Paddle & Surf, Inc.",
    "website": "http://www.paddlelkn.com/",
    "strategies": ["e", "p"],
    "thinktanks": [
      "At-Risk Residents",
      "Health",
      "Inviting Destination",
      "Natural Resources",
    ],
  },
  {
    "partner": "NC Med Assist",
    "website": "http://medassist.org/",
    "strategies": ["l", "p"],
  },
  {
    "partner": "NC State University Cooperative Extension",
    "website": "http://www.ces.ncsu.edu/",
    "strategies": ["p", "q"],
    "thinktanks": ["Culture Connections", "Learning", "Health"],
  },
  {
    "partner": "NC Sustainable Energy Association",
    "website": "http://www.energync.org/?",
    "strategies": ["t"],
    "thinktanks": ["Economic Competitiveness", "Natural Resources"],
  },
  {
    "partner": "Northeastern University - Charlotte Graduate Campus",
    "website": "http://www.northeastern.edu/charlotte/",
    "strategies": ["f", "n", "o", "u"],
    "thinktanks": ["Economic Competitiveness", "Learning"],
  },
  {
    "partner": "Novant Health",
    "website": "https://www.novanthealth.org/presbyterian-medical-center.aspx",
    "strategies": ["f", "p"],
  },
  {
    "partner": "Packard Place",
    "website": "http://packardplace.us/",
    "strategies": ["c", "e", "f", "o", "u"],
    "thinktanks": ["Economic Competitiveness", "Redevelopment"],
  },
  {
    "partner": "Piedmont Natural Gas",
    "website": "http://www.piedmontng.com/",
    "strategies": ["f", "h", "s", "t"],
    "thinktanks": ["Economic Competitiveness", "Learning", "Natural Resources"],
  },
  {
    "partner": "Professional Services Industry (PSI)",
    "website": "https://www.psiusa.com/",
    "thinktanks": [
      "Accessibility",
      "Economic Competitiveness",
      "Health",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Project for Innovation, Energy and Sustainability",
    "website": "http://www.pies-northcarolina.org/",
    "strategies": ["e", "f", "h", "t"],
    "thinktanks": [
      "Economic Competitiveness",
      "Inviting Destination",
      "Learning",
      "Natural Resources",
    ],
  },
  {
    "partner": "Queen City FinTech",
    "website": "http://www.qcfintech.co/",
    "thinktanks": ["Economic Competitiveness"],
  },
  {
    "partner": "Queen City Forward",
    "website": "http://queencityforward.org/",
    "strategies": ["c", "e", "f", "o"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
      "Inviting Destination",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "REBIC",
    "website": "http://rebiccharlotte.com/",
    "strategies": ["c", "e", "f", "g", "s"],
    "thinktanks": ["Redevelopment"],
  },
  {
    "partner": "ReCommunity",
    "website": "http://www.recommunity.com/",
    "strategies": ["e", "t"],
    "thinktanks": ["Learning", "Natural Resources"],
  },
  {
    "partner": "Safe Kids Charlotte-Mecklenburg",
    "website": "http://www.safekidscharmeck.org/",
    "strategies": ["a", "d", "n", "p", "u"],
    "thinktanks": ["Accessibility", "Health", "Safe Community"],
  },
  {
    "partner": "Salvation Army",
    "website": "http://www.salvationarmycarolinas.org/charlotte/home/",
    "strategies": ["l", "t"],
  },
  {
    "partner": "Sierra Club Central Piedmont",
    "website": "http://charlottesierraclub.org/",
    "strategies": ["q", "t"],
    "thinktanks": ["Accessibility", "Natural Resources"],
  },
  {
    "partner": "Mecklenburg County Smart Start",
    "website": "http://www.smartstartofmeck.org/",
    "strategies": ["n"],
  },
  {
    "partner": "Southminster",
    "website": "http://www.southminster.org/",
    "thinktanks": ["Accessibility", "At-Risk Residents", "Health"],
  },
  {
    "partner": "SPICE",
    "thinktanks": ["Learning"],
  },
  {
    "partner": "Sustain Charlotte",
    "website": "http://www.sustaincharlotte.org/",
    "strategies": ["e", "q", "s"],
    "thinktanks": [
      "Accessibility",
      "Culture Connections",
      "Economic Competitiveness",
      "Inviting Destination",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Teen Health Connection",
    "website": "http://www.teenhealthconnection.org/",
    "strategies": ["i", "p", "r"],
    "thinktanks": ["At-Risk Residents", "Health", "Safe Community"],
  },
  {
    "partner": "The Learning Collaborative",
    "website": "http://www.tlccharlotte.org/",
    "strategies": ["n", "o", "u"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Learning",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "The Relatives - National Safe Place",
    "website": "http://www.therelatives.org/relatives-new/safe-place-week",
    "strategies": ["a", "d", "j"],
    "thinktanks": ["At-Risk Residents", "Safe Community"],
  },
  {
    "partner": "Town of Davidson",
    "website": "http://www.ci.davidson.nc.us/",
    "strategies": [
      "a",
      "b",
      "c",
      "d",
      "e",
      "f",
      "g",
      "h",
      "i",
      "j",
      "k",
      "m",
      "p",
      "q",
      "r",
      "s",
      "t",
      "u",
    ],
    "thinktanks": ["Safe Community"],
  },
  {
    "partner": "Town of Huntersville",
    "website": "http://www.huntersville.org/",
    "strategies": [
      "a",
      "b",
      "c",
      "d",
      "e",
      "f",
      "g",
      "h",
      "i",
      "j",
      "k",
      "m",
      "p",
      "q",
      "r",
      "s",
      "t",
      "u",
    ],
    "thinktanks": [
      "Economic Competitiveness",
      "Inviting Destination",
      "Safe Community",
    ],
  },
  {
    "partner": "Town of Matthews",
    "website": "http://www.matthewsnc.gov/",
    "strategies": [
      "a",
      "b",
      "c",
      "d",
      "e",
      "f",
      "g",
      "h",
      "i",
      "j",
      "k",
      "m",
      "p",
      "q",
      "r",
      "s",
      "t",
      "u",
    ],
  },
  {
    "partner": "Town of Mint Hill",
    "website": "http://minthill.com/",
    "strategies": [
      "a",
      "b",
      "c",
      "d",
      "e",
      "f",
      "g",
      "h",
      "i",
      "j",
      "k",
      "m",
      "p",
      "q",
      "r",
      "s",
      "t",
      "u",
    ],
  },
  {
    "partner": "Town of Pineville",
    "website": "https://www.pinevillenc.gov/",
    "strategies": [
      "a",
      "b",
      "c",
      "d",
      "e",
      "f",
      "g",
      "h",
      "i",
      "j",
      "k",
      "m",
      "p",
      "q",
      "r",
      "s",
      "t",
      "u",
    ],
  },
  {
    "partner": "Trees Charlotte",
    "website": "http://treescharlotte.org/",
    "strategies": ["q", "s"],
    "thinktanks": ["Natural Resources"],
  },
  {
    "partner": "UNC Charlotte  ",
    "website": "http://www.uncc.edu/",
    "strategies": ["b", "e", "f", "h", "j", "n", "o", "p", "q", "u"],
    "thinktanks": [
      "Accessibility",
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
      "Inviting Destination",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "UNCC Urban Institute",
    "website": "http://ui.uncc.edu/",
    "strategies": ["a", "e", "j", "l", "o", "q"],
    "thinktanks": [
      "At-Risk Residents",
      "Accessibility",
      "Culture Connections",
      "Health",
      "Natural Resources",
      "Redevelopment",
    ],
  },
  {
    "partner": "USGBC - North Carolina Chapter",
    "website": "http://www.usgbcnc.org/?page=Charlotte",
    "strategies": ["c", "g", "s", "t"],
    "thinktanks": [
      "Accessibility",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
      "Natural Resources",
      "Safe Community",
      "Redevelopment",
    ],
  },
  {
    "partner": "United Way",
    "website": "http://www.uwcentralcarolinas.org/",
    "strategies": ["c", "j", "l", "u"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Health",
      "Learning",
      "Redevelopment",
    ],
  },
  {
    "partner": "University City Partners",
    "website": "http://universitycitypartners.org/",
    "strategies": ["b", "c", "d", "e", "f", "g", "h", "i", "l", "o", "q", "s"],
    "thinktanks": [
      "Accessibility",
      "Economic Competitiveness",
      "Health",
      "Inviting Destination",
      "Learning",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Urban Eagles",
    "website":
      "http://www.charlotteeagles.com/community/urbanministry/index_E.html",
    "thinktanks": ["Culture Connections"],
  },
  {
    "partner": "Urban League",
    "website": "http://www.urbanleaguecc.org/",
    "strategies": ["c", "j", "l", "u"],
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Economic Competitiveness",
      "Health",
      "Learning",
      "Natural Resources",
      "Redevelopment",
      "Safe Community",
    ],
  },
  {
    "partner": "Ventureprise",
    "website": "https://ventureprise.org/",
    "strategies": ["c", "e", "f", "n", "o", "u"],
    "thinktanks": ["Economic Competitiveness"],
  },
  {
    "partner": "Vision Ventures",
    "website": "http://visionventures.net/",
    "strategies": ["g", "t"],
    "thinktanks": [
      "Accessibility",
      "Health",
      "Natural Resources",
      "Redevelopment",
    ],
  },
  {
    "partner": "Wake Forest University School of Business",
    "website": "http://business.wfu.edu/",
    "strategies": ["f", "n", "o", "u"],
  },
  {
    "partner": "Wise Transitions",
    "website": "https://wisetransitionsnow.com/",
    "thinktanks": ["Accessibility", "Health"],
  },
  {
    "partner": "YWCA",
    "website": "https://ywcacentralcarolinas.org/",
    "thinktanks": [
      "At-Risk Residents",
      "Culture Connections",
      "Health",
      "Safe Community",
    ],
  },
]
